name: Deploy to Render
on:
  push:
    branches:
      - main

# Your workflows jobs.
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Render
      uses: render-iac/github-actions-render@1.0.0
      with:
        renderEmail: ${{ secrets.RENDER_EMAIL }}
        renderPassword: ${{ secrets.RENDER_PASSWORD }}
        renderAccount: Ninad Karlekar
        renderService: RealEstatePrediction
        dockerfile_directory: ./
        dockerfile_name: Dockerfile

